export const WORDS = ['story', 
'ocean', 'salty', 'water', 'thing', 'parts', 'their', 'lives', 'alien', 'heard', 'never', 
'could', 'price', 'hands', 'cells', 'world', 'flies', 'sleep', 'death', 'sound', 'there', 'greed', 'until', 
'cried', 'touch', 'proud', 'shame', 'tears', 'words', 'heart', 'count', 'still', 'being', 'keeps', 'trust', 'river', 'clear', 'light', 
'waste', 'heavy', 'other', 'rocks', 'given', 'makes', 'these', 'right', 'loves', 'guess', 'roses', 'going', 'pluck', 'would', 'glued', 'takes', 'plays', 
'fixed', 'lungs', 'comes', 'baths', 'feeds', 'stuck', 'grows', 'walks', 'after', 'which', 'lines', 'poems', 'every', 'spill', 'pages', 'proof', 'lived', 'while', 'value', 
'might', 'wiped', 'scars', 'piece', 'enjoy', 'scent', 'inked', 'front', 'sorts', 'kinds', 'about', 'times', 'baggy', 'under', 'shoes', 'curve', 'angry', 'black', 'magic', 'voice', 'speak', 'laugh', 
'tired', 'rainy', 'again', 'cycle', 'paths', 'those', 'speed', 'night', 'rises', 'carry', 'asked', 'doesn', 'small', 'stems', 'green', 'table', 'gases', 'tight', 'trail', 'place', 'looks', 'raped', 'doing', 'woman',
 'blame', 'blind', 'catch', 'sorry', 'bring', 'peace', 'hunts', 'loved', 
'cries', 'wrong', 'crier', 'close', 'group', 'cause', 'terms', 'happy', 'offer', 'found', 'empty', 'hopes', 'devil', 'where', 'rains', 'winds', 'facts', 'worth', 'spark', 'scary', 'dream', 'stage', 'stars', 
'drops', 'drain', 'stuff', 'space', 'kinda', 'plane', 'fails', 'image', 'needs', 'glass', 'floor', 'below', 'bones', 'sweet', 'belly', 'poets', 'girls', 'novel', 'forms', 'grade', 'goals', 'anger', 'today', 
'mourn', 'first', 'moved', 'quite', 'ashes', 'weren', 'depth', 'width', 'alive', 'laser', 'lover', 'write', 'reads', 'brain', 'diary', 'books', 'money', 'maybe', 'ahead', 'limit', 'truly', 'tends', 'meant', 
'blurt', 'blood', 'worry', 'petal', 'yours', 'weeks', 'later', 'irony', 'bliss', 'toxic', 'flesh', 'earth', 'kills', 'blows', 'north', 'sinks', 'south', 'mucus', 'sweep', 'think', 'mouth', 'haunt', 'roots', 
'attic', 'adopt', 'white', 'birth', 'owner', 'hours', 'years', 'thief', 'often', 'feels', 'shift', 'utter', 'young', 'force', 'froze', 'taken', 'share', 'fairy', 'tales', 'sunny', 'skies', 'tummy', 'noise', 
'couch', 'cream', 'phone', 'vivid', 'limbs', 'hears', 'thank', 'sight', 'early', 'finds', 'point', 'knows', 'least', 'flame', 'lousy', 'noisy', 'stare', 'sense', 'spent', 'rides', 'texts', 'calls', 'weird', 
'shell', 'spoon', 'brief', 'fruit', 'fully', 'funny', 'beats', 'chest', 'dance', 'piano', 'smell', 'turns', 'whiff', 'hoody', 'bench', 'trees', 'tells', 'crazy', 'liked', 'nails', 'watch', 'guest', 'shall', 
'payed', 'nurse', 'known', 'worse', 'state', 'order', 'slept', 'faith', 'twice', 'smile', 'crave', 'draws', 'shiny', 'daily', 'bread', 'talks', 'aware', 'music', 'angel', 'midst', 'newly', 'blank', 'serve', 
'throw', 'trash', 'ended', 'means', 'tried', 'leave', 'alone', 'bombs', 'study', 'whole', 'teeth', 'stops', 'reach', 'pills', 'power', 'gives', 'dryer', 'broke', 'wrote', 'blush', 'brown', 'start', 'stone', 'drown',
 'emoji', 'truth', 'claim', 'trend', 'style', 'cheap', 'shyly']